language: python
sudo: false

python:
    - 3.6

matrix:
  include:
    - python: 3.6
      env:
        - STYLE=1
    - python: 3.6
      env:
        - COVERAGE=1
    - python: 3.6
      env:
        - NOTEBOOKS=1

before_install:
    - python -m pip install --upgrade pip
    - pip install --upgrade virtualenv
    - if [ "${STYLE}" == "1" ]; then
        pip install flake8;
      fi
    - if [ "${COVERAGE}" == "1" ]; then
        pip install coverage coveralls codecov pytest==4.1 pytest-cov;
      fi
    - if [ "${NOTEBOOKS}" == "1" ]; then
        pip install pytest jupyter nbval;
      fi

install:
    - python setup.py install

script:
    - |
      if [ "${STYLE}" == "1" ]; then
          flake8 atlasreader
      elif [ "${COVERAGE}" == "1" ]; then
              TEST_ARGS="--cov-report term-missing --cov=atlasreader";
              py.test ${TEST_ARGS} atlasreader;
      elif [ "${NOTEBOOKS}" == "1" ]; then
          for n in `ls notebooks/*ipynb`
          do
              pytest --nbval-lax -v -s ${n};
          done
      fi

after_success:
    - if [ "${COVERAGE}" == "1" ]; then
          coveralls; codecov;
      fi
